dist: xenial

language: generic

jdk:
  - oraclejdk8

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential
      - valgrind

env:
  global:
    - INSTALL_CACHE=$HOME/install-cache
    - DOWNLOAD_ROOT=$HOME/download-root
    - JOBS=2

install:
  - source .ci/setup_env.sh

cache:
  apt: true
  directories:
    - $INSTALL_CACHE

script:
  - prove -r t
