name: Lint

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - uses: Jayrgo/luacheck-action@01594c6841054ef52fe52c0711b1a9159df3b461 # v1
      name: luacheck
      with:
        # List of files, directories and rockspecs to check.
        # Default: .
        files: 'lualib'

        # Path to configuration file.
        # Default: .luacheckrc
        config: '.luacheckrc'

        # Arguments passed to luacheck.
        # Default: -q
        args: '-q'
