name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
        # TODO: arm64
        - openresty: "1.19.3.2"
          luarocks: "3.7.0"
          openssl: "1.1.1k"
        - openresty: "1.19.9.1"
          luarocks: "3.8.0"
          openssl: "1.1.1m"
        - openresty: "1.21.4.1"
          luarocks: "3.9.1"
          openssl: "1.1.1q"

    env:
      JOBS: 1  # must be 1 as socket tests interfere with each other

      INSTALL_ROOT: /home/runner/work/install-root
      DOWNLOAD_ROOT: /home/runner/work/download-root

      OPENSSL_INSTALL: /home/runner/work/install-root/openssl
      OPENSSL_DIR: /home/runner/work/install-root/openssl
      OPENRESTY_INSTALL: /home/runner/work/install-root/openresty
      LUAROCKS_INSTALL: /home/runner/work/install-root/luarocks

      BUILD_TOOLS_DOWNLOAD: /home/runner/work/download-root/kong-build-tools
      BUILD_TOOLS_BRANCH: master

      OPENRESTY: ${{ matrix.openresty }}
      LUAROCKS: ${{ matrix.luarocks }}
      OPENSSL: ${{ matrix.openssl }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup cache
      uses: actions/cache@v2
      id: cache-deps
      with:
        path: |
          ${{ env.BUILD_ROOT }}
        key: ${{ hashFiles('src/**', 'lualib/**', '.github/workflows/tests.yml') }}

    - name: Install packages
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        sudo apt update
        sudo apt install libyaml-dev valgrind libprotobuf-dev cpanminus net-tools libpcre3-dev build-essential

    - name: Build Kong
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd kong
        branch=${GITHUB_HEAD_REF}
        branch=$(echo "$branch" | sed 's/\//\\\//g')
        sed -i "s/KONG_NGINX_MODULE_BRANCH=.\+/KONG_NGINX_MODULE_BRANCH=${branch}/" .requirements
        cat .requirements
        make build-kong
        make build-venv
        BUILD_PREFIX=$BUILD_ROOT/kong-dev
        export PATH="$BUILD_PREFIX/bin:$BUILD_PREFIX/openresty/nginx/sbin:$BUILD_PREFIX/openresty/bin:$PATH"
        chmod +rw -R $BUILD_PREFIX
        nginx -V
        ldd $(which nginx)
        luarocks

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Load build cache
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.BUILD_ROOT }}
        key: ${{ hashFiles('src/**', 'lualib/**', '.github/workflows/tests.yml') }}

    - name: Install packages
      run: |
        sudo apt update
        sudo apt-get install -qq -y cpanminus net-tools libpcre3-dev build-essential valgrind

    - name: Install Test::Nginx
      run: |
        if [ ! -e perl ]; then
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
          cp -r /usr/local/share/perl/ .
        else
          sudo cp -r perl /usr/local/share
        fi

    - name: Run Test
      run: |
        export PATH=$OPENSSL_INSTALL/bin:$OPENRESTY_INSTALL/nginx/sbin:$OPENRESTY_INSTALL/bin:$LUAROCKS_INSTALL/bin:$PATH
        export LD_LIBRARY_PATH=$OPENSSL_INSTALL/lib:$LD_LIBRARY_PATH # for openssl's CLI invoked in the test suite

        nginx -V
        resty -V
        luarocks --version
        openssl version

        eval `luarocks path`
        prove -j$JOBS -r t

    - name: Run Test with Valgrind
      run: |
        export PATH=$OPENSSL_INSTALL/bin:$OPENRESTY_INSTALL/nginx/sbin:$OPENRESTY_INSTALL/bin:$LUAROCKS_INSTALL/bin:$PATH
        export LD_LIBRARY_PATH=$OPENSSL_INSTALL/lib:$LD_LIBRARY_PATH # for openssl's CLI invoked in the test suite

        export TEST_NGINX_VALGRIND='--num-callers=100 -q --tool=memcheck --leak-check=full --show-possibly-lost=no --gen-suppressions=all --suppressions=valgrind.suppress --track-origins=yes' TEST_NGINX_TIMEOUT=60 TEST_NGINX_SLEEP=1
        export TEST_NGINX_USE_VALGRIND=1

        nginx -V
        resty -V
        luarocks --version
        openssl version

        eval `luarocks path`
        # fail if definite leak found
        prove -j$JOBS -r t 2>&1 | tee /dev/stderr | grep -q "match-leak-kinds: definite" && exit 1 || exit 0

