name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04

    env:
      JOBS: 2
      INSTALL_CACHE: /home/runner/work/install-cache
      DOWNLOAD_ROOT: /home/runner/work/download-root

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: |
          /home/runner/work/install-cache
        key: ${{ runner.os }}-${{ hashFiles('**/tests.yml') }}-${{ hashFiles('**/*.c', '**/*.h') }}

    - name: Setup tools
      run: |
        sudo apt-get update
        sudo apt-get install -qq -y postgresql cpanminus net-tools libpcre3-dev build-essential valgrind
        source .github/workflows/setup_env.sh

    - name: Run Test
      run: |
        echo $PATH
        echo LD_LIBRARY_PATH
        prove -r t

