name: Tests

on: [pull_request]

env:
  KONG_VERSION: master
  BUILD_ROOT: ${{ github.workspace }}/kong/bazel-bin/build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build dependencies
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Checkout Kong source code
      uses: actions/checkout@v3
      with:
        repository: kong/kong
        ref: ${{ env.KONG_VERSION }}
        path: kong

    - name: Lookup build cache
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.BUILD_ROOT }}
        key: ${{ hashFiles('src/**', 'lualib/**', '.github/workflows/tests.yml') }}

    - name: Install packages
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        sudo apt update
        sudo apt install libyaml-dev valgrind libprotobuf-dev cpanminus net-tools libpcre3-dev build-essential

    - name: Build Kong
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        cd kong
        branch=${GITHUB_HEAD_REF}
        branch=$(echo "$branch" | sed 's/\//\\\//g')
        sed -i "s/KONG_NGINX_MODULE_BRANCH=.\+/KONG_NGINX_MODULE_BRANCH=${branch}/" .requirements
        cat .requirements
        make build-kong
        make build-venv
        BUILD_PREFIX=$BUILD_ROOT/kong-dev
        export PATH="$BUILD_PREFIX/bin:$BUILD_PREFIX/openresty/nginx/sbin:$BUILD_PREFIX/openresty/bin:$PATH"
        chmod +rw -R $BUILD_PREFIX
        nginx -V
        ldd $(which nginx)
        luarocks

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Load build cache
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.BUILD_ROOT }}
        key: ${{ hashFiles('src/**', 'lualib/**', '.github/workflows/tests.yml') }}

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install libyaml-dev valgrind libprotobuf-dev cpanminus net-tools libpcre3-dev build-essential

    - name: Install Test::Nginx
      run: |
        if [ ! -e perl ]; then
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)
          cp -r /usr/local/share/perl/ .
        else
          sudo cp -r perl /usr/local/share
        fi

    - name: Run Test
      run: |
        source ${{ env.BUILD_ROOT }}/kong-dev-venv.sh

        nginx -V
        resty -V
        luarocks --version
        openssl version

        prove -r t

    - name: Run Test with Valgrind
      run: |
        source ${{ env.BUILD_ROOT }}/kong-dev-venv.sh

        export TEST_NGINX_VALGRIND='--num-callers=100 -q --tool=memcheck --leak-check=full --show-possibly-lost=no --gen-suppressions=all --suppressions=valgrind.suppress --track-origins=yes' TEST_NGINX_TIMEOUT=60 TEST_NGINX_SLEEP=1
        export TEST_NGINX_USE_VALGRIND=1

        nginx -V
        resty -V
        luarocks --version
        openssl version

        # fail if definite leak found
        prove -r t 2>&1 | tee /dev/stderr | grep -q "match-leak-kinds: definite" && exit 1 || exit 0
